baseURL = 'https://stabatmater.info/'
languageCode = 'en'
title = 'Stabat Mater Foundation'
publishDir = 'docs'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Composers'
    pageRef = 'stabat-mater-composer'
    weight = 2
  [[menu.main]]
    name = 'About'
    pageRef = 'stabat-mater-foundation'
    weight = 3
